name: test_fast_linux

###  https://github.com/arita37/awesome-actions#static-analysis

on:
  push:
    branches: 

 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
      
    #- uses: actions/cache@v1
    #  id: cache
    #  with:
    #    path: ~/.cache/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #    restore-keys: |
    #      ${{ runner.os }}-pip-
   


    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/requirements_fake.txt') }}

          

    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r requirements.txt


    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements_fake.txt


    - name: Install repo
      run: pip install -e . -r requirements.txt  --no-deps


    - name: Repo Check
      run: |
           python -c "import mlmodels,os ; print(mlmodels); print(os)"
           ml_test --do test_import


    ########  Test running 
    - name: ml_optim
      run: ml_optim


    - name: ml_models
      run: ml_models


    #- name: ml_test
    #  run: ml_test
      
         



# https://ianwhitestone.work/AWS-Serverless-Deployments-With-Github-Actions/
#
#
#
#
